package com.example.demo.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Entity class representing a Post in the database
 * Lớp Entity đại diện cho một bài viết (Post) trong cơ sở dữ liệu
 *
 * Relationship / Quan hệ:
 *   - Many Posts belong to ONE User (Nhiều bài viết thuộc về MỘT user)
 *   - ManyToOne: Post -> User (Nhiều-một: Bài viết -> User)
 *
 * @Entity: Marks this class as a JPA entity (đánh dấu lớp này là một JPA entity)
 * @Table: Mapped to "posts" table in database (ánh xạ tới bảng "posts" trong database)
 */
@Entity
@Table(name = "posts")
public class Post {

    /**
     * Primary key of the post, auto-generated by the database
     * Khóa chính của bài viết, được tự động tạo bởi database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    /**
     * Title of the post, cannot be null
     * Tiêu đề bài viết, không được để trống
     */
    @Column(nullable = false)
    private String title;

    /**
     * Content/body of the post, stored as TEXT to allow long content
     * Nội dung bài viết, lưu dạng TEXT để cho phép nội dung dài
     */
    @Column(columnDefinition = "TEXT")
    private String content;

    /**
     * Post status: PUBLISHED, DRAFT, ARCHIVED
     * Trạng thái bài viết: PUBLISHED (đã đăng), DRAFT (nháp), ARCHIVED (đã lưu trữ)
     */
    @Column(nullable = false)
    private String status = "PUBLISHED";

    /**
     * Timestamp when the post was created, auto-set on creation
     * Thời điểm tạo bài viết, tự động được gán khi tạo
     *
     * @Column(updatable = false): This field is set once and never changed
     *                              Trường này được đặt một lần và không bao giờ thay đổi
     */
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp of the last update, auto-set on each update
     * Thời điểm cập nhật lần cuối, tự động được cập nhật mỗi lần thay đổi
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * Many-to-One relationship: Many posts belong to ONE user
     * Quan hệ nhiều-một: Nhiều bài viết thuộc về MỘT user
     *
     * @ManyToOne: Defines the Many-to-One relationship (định nghĩa quan hệ nhiều-một)
     * @JoinColumn: Specifies the foreign key column "user_id" in the posts table
     *              Chỉ định cột khóa ngoại "user_id" trong bảng posts
     * @JsonIgnoreProperties: Prevents infinite recursion when serializing to JSON
     *                         Ngăn chặn vòng lặp vô hạn khi serialize sang JSON
     *                         (Post -> User -> List<Post> -> Post -> ... )
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    private User user;

    // ==================== Lifecycle Hooks / Vòng đời Entity ====================

    /**
     * Automatically set createdAt and updatedAt before persisting to database
     * Tự động gán createdAt và updatedAt trước khi lưu vào database
     *
     * @PrePersist: Runs before INSERT operation (chạy trước khi thực hiện INSERT)
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    /**
     * Automatically update the updatedAt field before each update
     * Tự động cập nhật trường updatedAt trước mỗi lần update
     *
     * @PreUpdate: Runs before UPDATE operation (chạy trước khi thực hiện UPDATE)
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    // ==================== Constructors / Hàm khởi tạo ====================

    /**
     * Default no-args constructor (required by JPA)
     * Hàm khởi tạo mặc định không tham số (bắt buộc bởi JPA)
     */
    public Post() {
    }

    /**
     * Parameterized constructor to create a Post
     * Hàm khởi tạo có tham số để tạo bài viết
     *
     * @param title   Post title (Tiêu đề bài viết)
     * @param content Post content (Nội dung bài viết)
     * @param status  Post status (Trạng thái bài viết)
     * @param user    The author of the post (Tác giả bài viết)
     */
    public Post(String title, String content, String status, User user) {
        this.title = title;
        this.content = content;
        this.status = status;
        this.user = user;
    }

    // ==================== Getters and Setters / Các phương thức get và set ====================

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    // ==================== toString / Hiển thị ====================

    @Override
    public String toString() {
        return "Post{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", status='" + status + '\'' +
                ", createdAt=" + createdAt +
                ", userId=" + (user != null ? user.getId() : null) +
                '}';
    }
}

