package com.example.demo.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import java.util.List;

/**
 * Entity class representing a User in the database
 * Lớp Entity đại diện cho một User trong cơ sở dữ liệu
 *
 * This class is mapped to the "users" table in the database
 * Lớp này được ánh xạ tới bảng "users" trong cơ sở dữ liệu
 *
 * @Entity: Marks this class as a JPA entity (đánh dấu lớp này là một JPA entity)
 * @Table: Specifies the table name in database (chỉ định tên bảng trong database)
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * Primary key of the user, auto-generated by the database
     * Khóa chính của user, được tự động tạo bởi database
     *
     * @Id: Marks this field as primary key (đánh dấu trường này là khóa chính)
     * @GeneratedValue: Auto-increment strategy (chiến lược tự tăng)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User's full name, cannot be null
     * Tên đầy đủ của user, không được để trống
     */
    @Column(nullable = false)
    private String name;

    /**
     * User's email address, must be unique and not null
     * Địa chỉ email của user, phải là duy nhất và không được để trống
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * User's phone number, optional field
     * Số điện thoại của user, trường tùy chọn
     */
    @Column
    private String phone;

    /**
     * User's address, optional field
     * Địa chỉ của user, trường tùy chọn
     */
    @Column
    private String address;

    /**
     * One-to-Many relationship: ONE user can have MANY posts
     * Quan hệ một-nhiều: MỘT user có thể có NHIỀU bài viết
     *
     * @OneToMany: Defines the One-to-Many relationship (định nghĩa quan hệ một-nhiều)
     * mappedBy = "user": The "user" field in Post class owns the relationship
     *                    Trường "user" trong lớp Post sở hữu quan hệ này
     * cascade = ALL: All operations on User cascade to Posts
     *                Tất cả thao tác trên User sẽ lan truyền sang Posts
     * orphanRemoval = true: Deleting User also deletes all their posts
     *                       Xóa User cũng sẽ xóa tất cả bài viết của họ
     * @JsonIgnore: Prevents infinite JSON loop (User -> Posts -> User -> ...)
     *              Ngăn chặn vòng lặp JSON vô hạn
     */
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonIgnore
    private List<Post> posts;

    // ==================== Constructors / Hàm khởi tạo ====================

    /**
     * Default no-args constructor (required by JPA)
     * Hàm khởi tạo mặc định không tham số (bắt buộc bởi JPA)
     */
    public User() {
    }

    /**
     * Parameterized constructor to create a User with all fields
     * Hàm khởi tạo có tham số để tạo User với tất cả các trường
     *
     * @param name    User's name (Tên user)
     * @param email   User's email (Email user)
     * @param phone   User's phone number (Số điện thoại user)
     * @param address User's address (Địa chỉ user)
     */
    public User(String name, String email, String phone, String address) {
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.address = address;
    }

    // ==================== Getters and Setters / Các phương thức get và set ====================

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public List<Post> getPosts() {
        return posts;
    }

    public void setPosts(List<Post> posts) {
        this.posts = posts;
    }

    // ==================== toString / Phương thức chuyển đổi thành chuỗi ====================

    /**
     * Returns a string representation of the User object (for debugging/logging)
     * Trả về chuỗi biểu diễn đối tượng User (dùng để debug/ghi log)
     */
    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", phone='" + phone + '\'' +
                ", address='" + address + '\'' +
                '}';
    }
}

